# Generated by Django 5.2.1 on 2025-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classmate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(upload_to="classmates/", verbose_name="Фото"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Электронная почта"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                ("photo", models.ImageField(upload_to="people/", verbose_name="Фото")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("head", "Академический руководитель"),
                            ("manager", "Менеджер"),
                        ],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="pages/")),
            ],
        ),
        migrations.CreateModel(
            name="StudyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название ОП")),
                ("url", models.URLField(verbose_name="Ссылка на ОП")),
                (
                    "description",
                    models.TextField(
                        verbose_name="Что я буду изучать / чему научусь / преимущества / перспективы"
                    ),
                ),
            ],
        ),
    ]
