# Generated by Django 5.2.1 on 2025-06-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "photo",
                    models.ImageField(upload_to="about_me/", verbose_name="Фото"),
                ),
                ("resume", models.TextField(verbose_name="Резюме")),
            ],
        ),
    ]
