# Generated by Django 5.2.1 on 2025-06-04 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="course",
            field=models.IntegerField(
                choices=[
                    (1, "1 курс"),
                    (2, "2 курс"),
                    (3, "3 курс"),
                    (4, "4 курс"),
                    (5, "5 курс"),
                ],
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Средний балл (GPA)",
            ),
        ),
    ]
